### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justified777**

### CODE REVIEW

**Comment by justified777** [comment]
I'm not sure where the AddApiKeyAuthorizationHeader came from but I dont' see a corresponding method in HttpClient so I updated the apikey type line to what worked for me.  Take it or leave it. :)

**Comment by jusbuc2k** [comment]
That's an extension method in the package Csg.ApiKeyGenerator. It's not strictly needed for the static key, but it's needed for the time-based keys, which is what you should be using I'll update the example to make sure that it's clear.

You should install the package Csg.ApiKeyGenerator from the myget public dev feed linked on the readme.

October 8, 2018 7:45 AM, "justified777" <notifications@github.com (mailto:%22justified777%22%20<notifications@github.com>)> wrote:
	I'm not sure where the AddApiKeyAuthorizationHeader came from but I dont' see a corresponding method in HttpClient so I updated the apikey type line to what worked for me. Take it or leave it. :)

**Comment by justified777** [comment]
​I figured there was something I was missing there.   I only dived into the apikey code to see what was going on there and figured a simple header would do the job.  i didn't look at the Tapikey stuff.


Thanks,


Ken


________________________________

**Comment by jusbuc2k** [comment]
The idea is that for testing with postman/swagger ui/etc you would use static keys that expire, and the time-based keys would be something for inter-service communication

JB

October 8, 2018 8:16 AM, "justified777" <notifications@github.com (mailto:%22justified777%22%20<notifications@github.com>)> wrote:
​I figured there was something I was missing there. I only dived into the apikey code to see what was going on there and figured a simple header would do the job. i didn't look at the Tapikey stuff.
Thanks,
Ken
________________________________

**Pull request closed without merging**
